#!/bin/bash
clear
# Run Betty on source files
betty main.h *.c

# Compile the program
if gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -Wno-format *.c -o printf; then
    ./printf
else
    echo "Compilation failed. Exiting..."
fi